name: test

on: 
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      matrix:
        version: [ '1.16', '1.17' ]
    name: Go ${{ matrix.version }}
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.version }}
    - if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v2
      with:
        ref: ${{ format('refs/pull/{0}/merge', github.event.number) }}
    - if: ${{ github.event_name == 'push' }}
      uses: actions/checkout@v2
    - if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
      run: make test
